services:
  cloud_chatops:
    image: harbor.stfc.ac.uk/stfc-cloud/cloud-chatops:8.1.2
    volumes:
      - /opt/chatops/secrets.yml/:/usr/src/app/secrets.yml
      - /opt/chatops/config.yml/:/usr/src/app/config.yml

  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    volumes:
      - /etc/chatops/config/:/usr/src/app/cloud_chatops/config/
    ports:
      - 80:80
      - 443:443
